package com.shopping;

// Generated Jan 6, 2016 3:15:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Attr generated by hbm2java
 */
@Entity
@Table(name = "attr", catalog = "shdb", uniqueConstraints = @UniqueConstraint(columnNames = "attr_code"))
public class Attr implements java.io.Serializable {

	private String id;
	private String attrCode;
	private String attrName;
	private String attrCate;
	private String lastUpdateBy;
	private Date lastUpdateTime;
	private Integer versionstamp;
	private Set<ProdAttr> prodAttrs = new HashSet<ProdAttr>(0);
	private Set<CateAttrSet> cateAttrSets = new HashSet<CateAttrSet>(0);

	public Attr() {
	}

	public Attr(String id, String attrCode) {
		this.id = id;
		this.attrCode = attrCode;
	}

	public Attr(String id, String attrCode, String attrName, String attrCate,
			String lastUpdateBy, Date lastUpdateTime, Integer versionstamp,
			Set<ProdAttr> prodAttrs, Set<CateAttrSet> cateAttrSets) {
		this.id = id;
		this.attrCode = attrCode;
		this.attrName = attrName;
		this.attrCate = attrCate;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdateTime = lastUpdateTime;
		this.versionstamp = versionstamp;
		this.prodAttrs = prodAttrs;
		this.cateAttrSets = cateAttrSets;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "attr_code", unique = true, nullable = false, length = 12)
	public String getAttrCode() {
		return this.attrCode;
	}

	public void setAttrCode(String attrCode) {
		this.attrCode = attrCode;
	}

	@Column(name = "attr_name", length = 45)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	@Column(name = "attr_cate", length = 3)
	public String getAttrCate() {
		return this.attrCate;
	}

	public void setAttrCate(String attrCate) {
		this.attrCate = attrCate;
	}

	@Column(name = "last_update_by", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "versionstamp")
	public Integer getVersionstamp() {
		return this.versionstamp;
	}

	public void setVersionstamp(Integer versionstamp) {
		this.versionstamp = versionstamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attr")
	public Set<ProdAttr> getProdAttrs() {
		return this.prodAttrs;
	}

	public void setProdAttrs(Set<ProdAttr> prodAttrs) {
		this.prodAttrs = prodAttrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attr")
	public Set<CateAttrSet> getCateAttrSets() {
		return this.cateAttrSets;
	}

	public void setCateAttrSets(Set<CateAttrSet> cateAttrSets) {
		this.cateAttrSets = cateAttrSets;
	}

}
