package com.shopping;

// Generated Jan 6, 2016 3:15:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CateAttrSet generated by hbm2java
 */
@Entity
@Table(name = "cate_attr_set", catalog = "shdb", uniqueConstraints = @UniqueConstraint(columnNames = "cate_attr_set_code"))
public class CateAttrSet implements java.io.Serializable {

	private String id;
	private Attr attr;
	private String cateAttrSetCode;
	private Boolean isMandatory;
	private String lastUpdateBy;
	private Date lastUpdateTime;
	private Integer versionstamp;
	private Set<Cate> cates = new HashSet<Cate>(0);

	public CateAttrSet() {
	}

	public CateAttrSet(String id, String cateAttrSetCode) {
		this.id = id;
		this.cateAttrSetCode = cateAttrSetCode;
	}

	public CateAttrSet(String id, Attr attr, String cateAttrSetCode,
			Boolean isMandatory, String lastUpdateBy, Date lastUpdateTime,
			Integer versionstamp, Set<Cate> cates) {
		this.id = id;
		this.attr = attr;
		this.cateAttrSetCode = cateAttrSetCode;
		this.isMandatory = isMandatory;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdateTime = lastUpdateTime;
		this.versionstamp = versionstamp;
		this.cates = cates;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attr_id")
	public Attr getAttr() {
		return this.attr;
	}

	public void setAttr(Attr attr) {
		this.attr = attr;
	}

	@Column(name = "cate_attr_set_code", unique = true, nullable = false, length = 12)
	public String getCateAttrSetCode() {
		return this.cateAttrSetCode;
	}

	public void setCateAttrSetCode(String cateAttrSetCode) {
		this.cateAttrSetCode = cateAttrSetCode;
	}

	@Column(name = "is_mandatory")
	public Boolean getIsMandatory() {
		return this.isMandatory;
	}

	public void setIsMandatory(Boolean isMandatory) {
		this.isMandatory = isMandatory;
	}

	@Column(name = "last_update_by", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "versionstamp")
	public Integer getVersionstamp() {
		return this.versionstamp;
	}

	public void setVersionstamp(Integer versionstamp) {
		this.versionstamp = versionstamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cateAttrSet")
	public Set<Cate> getCates() {
		return this.cates;
	}

	public void setCates(Set<Cate> cates) {
		this.cates = cates;
	}

}
