package com.shopping;

// Generated Jan 6, 2016 3:15:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CateCate generated by hbm2java
 */
@Entity
@Table(name = "cate_cate", catalog = "shdb")
public class CateCate implements java.io.Serializable {

	private String id;
	private Cate cateByCateIdChild;
	private Cate cateByCateIdParent;
	private String lastUpdateBy;
	private Date lastUpdateTime;
	private Integer versionstamp;

	public CateCate() {
	}

	public CateCate(String id, Cate cateByCateIdChild, Cate cateByCateIdParent) {
		this.id = id;
		this.cateByCateIdChild = cateByCateIdChild;
		this.cateByCateIdParent = cateByCateIdParent;
	}

	public CateCate(String id, Cate cateByCateIdChild, Cate cateByCateIdParent,
			String lastUpdateBy, Date lastUpdateTime, Integer versionstamp) {
		this.id = id;
		this.cateByCateIdChild = cateByCateIdChild;
		this.cateByCateIdParent = cateByCateIdParent;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdateTime = lastUpdateTime;
		this.versionstamp = versionstamp;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cate_id_child", nullable = false)
	public Cate getCateByCateIdChild() {
		return this.cateByCateIdChild;
	}

	public void setCateByCateIdChild(Cate cateByCateIdChild) {
		this.cateByCateIdChild = cateByCateIdChild;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cate_id_parent", nullable = false)
	public Cate getCateByCateIdParent() {
		return this.cateByCateIdParent;
	}

	public void setCateByCateIdParent(Cate cateByCateIdParent) {
		this.cateByCateIdParent = cateByCateIdParent;
	}

	@Column(name = "last_update_by", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "versionstamp")
	public Integer getVersionstamp() {
		return this.versionstamp;
	}

	public void setVersionstamp(Integer versionstamp) {
		this.versionstamp = versionstamp;
	}

}
