package com.shopping;

// Generated Jan 6, 2016 3:15:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Consumer generated by hbm2java
 */
@Entity
@Table(name = "consumer", catalog = "shdb", uniqueConstraints = @UniqueConstraint(columnNames = "user_id"))
public class Consumer implements java.io.Serializable {

	private String id;
	private User user;
	private String lastUpdateBy;
	private Date lastUpdateTime;
	private Integer versionstamp;

	public Consumer() {
	}

	public Consumer(String id, User user) {
		this.id = id;
		this.user = user;
	}

	public Consumer(String id, User user, String lastUpdateBy,
			Date lastUpdateTime, Integer versionstamp) {
		this.id = id;
		this.user = user;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdateTime = lastUpdateTime;
		this.versionstamp = versionstamp;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", unique = true, nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "last_update_by", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "versionstamp")
	public Integer getVersionstamp() {
		return this.versionstamp;
	}

	public void setVersionstamp(Integer versionstamp) {
		this.versionstamp = versionstamp;
	}

}
