package com.shopping;

// Generated Jan 6, 2016 3:15:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ProdAttr generated by hbm2java
 */
@Entity
@Table(name = "prod_attr", catalog = "shdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"prod_id", "attr_id" }))
public class ProdAttr implements java.io.Serializable {

	private String id;
	private Attr attr;
	private Prod prod;
	private String attrValue;
	private String lastUpdateBy;
	private Date lastUpdateTime;
	private Integer versionstamp;

	public ProdAttr() {
	}

	public ProdAttr(String id) {
		this.id = id;
	}

	public ProdAttr(String id, Attr attr, Prod prod, String attrValue,
			String lastUpdateBy, Date lastUpdateTime, Integer versionstamp) {
		this.id = id;
		this.attr = attr;
		this.prod = prod;
		this.attrValue = attrValue;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdateTime = lastUpdateTime;
		this.versionstamp = versionstamp;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attr_id")
	public Attr getAttr() {
		return this.attr;
	}

	public void setAttr(Attr attr) {
		this.attr = attr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prod_id")
	public Prod getProd() {
		return this.prod;
	}

	public void setProd(Prod prod) {
		this.prod = prod;
	}

	@Column(name = "attr_value", length = 120)
	public String getAttrValue() {
		return this.attrValue;
	}

	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue;
	}

	@Column(name = "last_update_by", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "versionstamp")
	public Integer getVersionstamp() {
		return this.versionstamp;
	}

	public void setVersionstamp(Integer versionstamp) {
		this.versionstamp = versionstamp;
	}

}
