package com.shopping;

// Generated Jan 6, 2016 3:15:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "shdb", uniqueConstraints = @UniqueConstraint(columnNames = "user_code"))
public class User implements java.io.Serializable {

	private String id;
	private String userCode;
	private String name;
	private String emailId;
	private String mobilePhone;
	private Set<Merchant> merchants = new HashSet<Merchant>(0);
	private Set<UserAuth> userAuths = new HashSet<UserAuth>(0);
	private Set<Consumer> consumers = new HashSet<Consumer>(0);
	private Set<Order> ordersForMerchantUserId = new HashSet<Order>(0);
	private Set<Order> ordersForConsumerUserId = new HashSet<Order>(0);

	public User() {
	}

	public User(String id, String userCode) {
		this.id = id;
		this.userCode = userCode;
	}

	public User(String id, String userCode, String name, String emailId,
			String mobilePhone, Set<Merchant> merchants,
			Set<UserAuth> userAuths, Set<Consumer> consumers,
			Set<Order> ordersForMerchantUserId,
			Set<Order> ordersForConsumerUserId) {
		this.id = id;
		this.userCode = userCode;
		this.name = name;
		this.emailId = emailId;
		this.mobilePhone = mobilePhone;
		this.merchants = merchants;
		this.userAuths = userAuths;
		this.consumers = consumers;
		this.ordersForMerchantUserId = ordersForMerchantUserId;
		this.ordersForConsumerUserId = ordersForConsumerUserId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "user_code", unique = true, nullable = false, length = 45)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email_id", length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "mobile_phone", length = 20)
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Merchant> getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Set<Merchant> merchants) {
		this.merchants = merchants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserAuth> getUserAuths() {
		return this.userAuths;
	}

	public void setUserAuths(Set<UserAuth> userAuths) {
		this.userAuths = userAuths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Consumer> getConsumers() {
		return this.consumers;
	}

	public void setConsumers(Set<Consumer> consumers) {
		this.consumers = consumers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByMerchantUserId")
	public Set<Order> getOrdersForMerchantUserId() {
		return this.ordersForMerchantUserId;
	}

	public void setOrdersForMerchantUserId(Set<Order> ordersForMerchantUserId) {
		this.ordersForMerchantUserId = ordersForMerchantUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByConsumerUserId")
	public Set<Order> getOrdersForConsumerUserId() {
		return this.ordersForConsumerUserId;
	}

	public void setOrdersForConsumerUserId(Set<Order> ordersForConsumerUserId) {
		this.ordersForConsumerUserId = ordersForConsumerUserId;
	}

}
